version: "3"
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 321qaz
      POSTGRES_DB: BookStore
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: BookStore
      DB_USER: postgres
      DB_PASSWORD: 321qaz
    volumes:
      - ./data:/app/data