version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: assignment_3
      DB_USER: postgres
      DB_PASSWORD: 321qaz
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=321qaz
      - POSTGRES_DB=assignment_3
    ports:
      - '5432:5432'

